name: GitHub Actions Test

on:
  push:
   branches: [ "main", "development" ]
  pull_request:
   branches: [ "main", "development" ]
  workflow_call:
  workflow_dispatch:

jobs:
 test:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v4

   - name: Install dependecies
     run: npm install

   - name: Run test
     run: npm test
     working-directory: backend/src